/** Standalone Agent Gateway API. Backends never own the app or transport. */
export { Gateway, createBackend } from './gateway/app.js'
export type { BackendFactory } from './gateway/app.js'
export { GatewayRouter } from './gateway/router.js'
export { StateStore } from './gateway/state.js'
export type { Backend, BackendEvent, BackendRequest, SessionOptions } from './backends/types.js'
export { BaseBackend } from './backends/types.js'
export { loadAppConfig, validateConfig, importConfig } from './app/config.js'
export type { AppConfig, Secrets } from './app/config.js'
export { startServer } from './app/server.js'

export type { ChannelAdapter, ChannelMessage, ChannelConnection, ChannelFactory } from './channels/types.js'
export type { ChannelConfig } from './gateway/config.js'
export { IMessageAdapter } from './channels/imessage.js'
export { WeixinAdapter } from './channels/weixin.js'
